version: "3.9"
services:
    mongo:
        image: "mongo"
        restart: "on-failure"
        ports:
        - "27017:27017"
        container_name: "merchantservice-mongo"
        volumes:
        - /data/db
            
    merchantservice:
        image: "merchantservice:latest"
        restart: "on-failure"
        ports:
        - "5000:80"
        container_name: "merchantservice"
        depends_on:
        - mongo
       
